// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Score.Infrastructure.Data;

#nullable disable

namespace Score.Infrastructure.Migrations;

[DbContext(typeof(ScoreDbContext))]
partial class ScoreDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Score.Core.Models.ScoreRecord", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("FirstName")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<int>("Score")
                .HasColumnType("int");

            b.Property<string>("SecondName")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");
            b.ToTable("Scores");
        });
#pragma warning restore 612, 618
    }
}
